language: bash
sudo: required
dist: bionic
env:
- OS=debian ARCH=amd64 DIST=bullseye
- OS=debian ARCH=armel DIST=bullseye QEMU_USER_STATIC=qemu-user-static
cache:
  directories:
  - "$HOME/cache"
before_install:
- sudo apt-add-repository -y ppa:ev3dev/tools
- sudo apt-get update
- sudo apt-get install --yes debhelper fakeroot pbuilder-ev3dev gobject-introspection $QEMU_USER_STATIC
- if [ -n "$QEMU_USER_STATIC" ]; then
    wget https://github.com/multiarch/qemu-user-static/releases/download/v5.0.0-2/qemu-arm-static;
    chmod +x qemu-arm-static;
    sudo mv qemu-arm-static /usr/bin/;
  fi
before_script:
- pbuilder-ev3dev base
- git checkout -B ev3dev-bullseye
script:
- pbuilder-ev3dev build
